# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_answer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form3(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 169)
        self.setStyleSheet("background-color: #282828")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.msg = QtWidgets.QLabel(Form)
        self.msg.setStyleSheet("color: #ffffff")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msg.sizePolicy().hasHeightForWidth())
        self.msg.setSizePolicy(sizePolicy)
        self.msg.setText("")
        self.msg.setObjectName("msg")
        self.gridLayout.addWidget(self.msg, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet('color: #ffffff')
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.save_answer = QtWidgets.QPushButton(Form)
        self.save_answer.setObjectName("save_answer")
        self.save_answer.setStyleSheet('background-color: #585757;'
                                       'color: #ffffff')
        self.gridLayout.addWidget(self.save_answer, 3, 1, 1, 1)
        self.sentence = QtWidgets.QTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sentence.sizePolicy().hasHeightForWidth())
        self.sentence.setSizePolicy(sizePolicy)
        self.sentence.setMaximumSize(QtCore.QSize(16777215, 40))
        self.sentence.setObjectName("sentence")
        self.sentence.setStyleSheet("background-color: #ffffff")
        self.gridLayout.addWidget(self.sentence, 1, 2, 1, 1)
        self.answer = QtWidgets.QTextEdit(Form)
        self.answer.setStyleSheet("background-color: #ffffff")
        self.answer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.answer.setObjectName("answer")
        self.gridLayout.addWidget(self.answer, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.label.setStyleSheet('color: #ffffff')
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Ответ"))
        self.save_answer.setText(_translate("Form", "Записать"))
        self.label.setText(_translate("Form", "Предложение"))
