# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calories_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(655, 400)
        self.setStyleSheet("background-color: #282828")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.start_wnd_with_user_variant = QtWidgets.QPushButton(Form)
        self.start_wnd_with_user_variant.setStyleSheet("background-color: #585757;"
                                                       "color: #ffffff")
        self.start_wnd_with_user_variant.setObjectName("start_wnd_with_user_variant")
        self.gridLayout.addWidget(self.start_wnd_with_user_variant, 4, 1, 1, 4)
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setObjectName("table")
        stylesheet = "QTabBar::{Background-color:rgb(190,1,1);}"
        self.table.setStyleSheet(stylesheet)
        self.gridLayout.addWidget(self.table, 1, 1, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)
        self.count = QtWidgets.QPushButton(Form)
        self.count.setObjectName("count")
        self.count.setStyleSheet("background-color: #585757;"
                                "color: #ffffff")
        self.gridLayout.addWidget(self.count, 3, 4, 1, 1)
        self.label = QLabel('Название продукта', self)
        self.label.setObjectName('label')
        self.label.setStyleSheet("color: #ffffff")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 5, 1, 1)
        self.input = QtWidgets.QLineEdit(Form)
        self.input.setObjectName("input")
        self.input.setStyleSheet("background-color: #ffffff")
        self.gridLayout.addWidget(self.input, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start_wnd_with_user_variant.setText(_translate("Form", "Ввести свой вариант"))
        self.count.setText(_translate("Form", "Посчитать калории"))
