# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 614)
        self.setStyleSheet("background-color: #282828;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setStyleSheet("background-color: #585757;"
                                    "color: #ffffff")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send.sizePolicy().hasHeightForWidth())
        self.send.setSizePolicy(sizePolicy)
        self.send.setObjectName("send")
        self.send.setMaximumSize(QtCore.QSize(266, 50))
        self.gridLayout.addWidget(self.send, 2, 4, 1, 1)
        self.input = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input.sizePolicy().hasHeightForWidth())
        self.input.setSizePolicy(sizePolicy)
        self.input.setMaximumSize(QtCore.QSize(16777215, 50))
        self.input.setBaseSize(QtCore.QSize(0, 20))
        self.input.setStyleSheet("background-color: #ffffff")
        self.input.setObjectName("input")
        self.gridLayout.addWidget(self.input, 2, 1, 1, 3)
        self.math_btn = QtWidgets.QPushButton(self.centralwidget)
        self.math_btn.setObjectName("math_btn")
        self.math_btn.setText('Сколько будет')
        self.math_btn.setStyleSheet("background-color: #585757;"
                                    "color: #ffffff")
        self.gridLayout.addWidget(self.math_btn, 4, 1, 1, 1)
        self.calories_btn = QtWidgets.QPushButton(self.centralwidget)
        self.calories_btn.setStyleSheet("background-color: #585757;"
                                    "color: #ffffff")
        self.calories_btn.setObjectName("calories_btn")
        self.calories_btn.setText('Посчитай калории')
        self.gridLayout.addWidget(self.calories_btn, 4, 2, 1, 1)
        self.start_talk = QtWidgets.QPushButton(self.centralwidget)
        self.start_talk.setObjectName("start_talk")
        self.start_talk.setStyleSheet("background-color: #585757;"
                                    "color: #ffffff")
        self.start_talk.setText('Давай поболтаем')
        self.gridLayout.addWidget(self.start_talk, 4, 3, 1, 1)
        self.what_can = QtWidgets.QPushButton(self.centralwidget)
        self.what_can.setObjectName("what_can")
        self.what_can.setText('Что ты можешь?')
        self.what_can.setStyleSheet("background-color: #585757;"
                                    "color: #ffffff")
        self.gridLayout.addWidget(self.what_can, 4, 4, 1, 1)
        self.get_user_answer = QtWidgets.QPushButton(self.centralwidget)
        self.get_user_answer.setObjectName("get_user_answer")
        self.get_user_answer.setStyleSheet("background-color: #585757;"
                                    "color: #ffffff")
        self.get_user_answer.setText('Неверный ответ? Нажмите на кнопку и введите свой вариант')
        self.gridLayout.addWidget(self.get_user_answer, 3, 1, 1, 4)
        self.messages = QtWidgets.QListWidget(self.centralwidget)
        self.messages.setObjectName("messages")
        self.gridLayout.addWidget(self.messages, 1, 1, 1, 4)
        self.messages.setStyleSheet("background-color: #ffffff")
        spacerItem3 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send.setText(_translate("MainWindow", "Отправить"))
