# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_calories.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(630, 199)
        self.setStyleSheet('background-color: #282828')
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.calories = QtWidgets.QLineEdit(Form)
        self.calories.setObjectName("calories")
        self.calories.setStyleSheet('background-color: #ffffff')
        self.gridLayout.addWidget(self.calories, 4, 2, 1, 1)
        self.fats = QtWidgets.QLineEdit(Form)
        self.fats.setObjectName("fats")
        self.fats.setStyleSheet('background-color: #ffffff')
        self.gridLayout.addWidget(self.fats, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet('color: #ffffff')
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.save = QtWidgets.QPushButton(Form)
        self.save.setObjectName("save")
        self.save.setStyleSheet('background-color: #585757')
        self.gridLayout.addWidget(self.save, 5, 1, 1, 2)
        self.error = QtWidgets.QLabel(Form)
        self.error.setText("")
        self.error.setObjectName("error")
        self.error.setStyleSheet('color: #ffffff')
        self.gridLayout.addWidget(self.error, 6, 1, 1, 2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.label.setStyleSheet('color: #ffffff')
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.title = QtWidgets.QLineEdit(Form)
        self.title.setObjectName("lineEdit")
        self.title.setStyleSheet('background-color: #ffffff')
        self.gridLayout.addWidget(self.title, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet('color: #ffffff')
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.carbohydrates = QtWidgets.QLineEdit(Form)
        self.carbohydrates.setStyleSheet('background-color: #ffffff')
        self.carbohydrates.setObjectName("carbohydrates")
        self.gridLayout.addWidget(self.carbohydrates, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 1)
        self.proteins = QtWidgets.QLineEdit(Form)
        self.proteins.setObjectName("proteins")
        self.proteins.setStyleSheet('background-color: #ffffff')
        self.gridLayout.addWidget(self.proteins, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet('color: #ffffff')
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.label_5.setStyleSheet('color: #ffffff')
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Углеводы"))
        self.save.setText(_translate("Form", "Ввод"))
        self.label.setText(_translate("Form", "Белки"))
        self.label_3.setText(_translate("Form", "Жиры"))
        self.label_4.setText(_translate("Form", "Калории"))
        self.label_5.setText(_translate("Form", "Название продукта"))
